### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by XSR1** [RvdHout/IIS-GeoIP2block-Module#1]
Thanks for releasing this!

Is't possible to add IPv6 support?

**Comment by RvdHout** [comment]
For me, it isn't...I do not have access to a single IPv6 connection so this is somewhat impossible for me to test...but feel free to make a fork!

**Comment by davidcie** [comment]
Did just that when Event Log errors bugged me enough. If interested you can check [my fork](https://github.com/davidcie/IIS-GeoIP2block-Module) and/or the relevant [feature branch](https://github.com/davidcie/IIS-GeoIP2block-Module/tree/feature-ipv6). Please note no extensive testing went into baking IPv6 support but at the very least EL errors are gone.

**Comment by RvdHout** [comment]
@davidcie
Nice!

I used the MaxMind sources simply because i could leave unused stuff out and therefor keep the size of the assembly smaller... compare mine (100kb) with yours (871kb), quite a difference if you ask me!

**Comment by davidcie** [comment]
Sure thing, though I get about 590kB in release mode. 

On this subject though... not familiar enough with IIS module lifecycle but is configuration data loaded once and reused for every request in a particular app pool or should the module use static variables to avoid a big memory and CPU penalty in a highly concurrent enviroment?

**Comment by RvdHout** [comment]
Not sure, but i suspect to be loaded once while loading AppPool as you pointed out

**Comment by davidcie** [comment]
I generally prefer including packages rather than manually copying and updating sources because it makes it easier to keep up with security and general patches. Having said that, these are probably tiny sources and the attack surface is minimal with the way GeoBlock is used inside of IIS so other than habit and personal preference there probably isn't a clear objective case for going that way over your approach.

Will try to have a look at how often the module is loaded by IIS when I have time. If it is indeed once per site or thread then in my view a couple hundred kB make little difference in the general scheme of things. However, if IIS loads the module for every request... then we certainly better squeeze every last unnecessary kB out of this badboy!
