### ISSUE TITLE
Building instructions

### ISSUE THREAD

**Issue by davidcie** [RvdHout/IIS-GeoIP2block-Module#2]
First of all thank you for updating this module for IIS 10. It would be nice if you could provide a compiled release and/or outline how to build the dll. I have a working VS 2017 setup but a missing `Microsoft.Web.Management` reference that I'm having difficulty locating (installing Windows 8.1 SDK did not solve the problem).

**Comment by RvdHout** [comment]
Hi Dawid... sorry about the missing build instructions, the Microsoft.Web.Administration.dll and Microsoft.Web.Management.dll cannout be distributed due to legal issues

The Microsoft.Web.Administration assembly is found in C:\Windows\System32\inetsrv\ on my machine.it is installed as part of IIS. The assembly is also in the GAC.

For IIS 8 and up, you could run this command to enable the IIS Management tools:
`Dism /online /Enable-Feature /FeatureName:IIS-WebServerManagementTools /All`
Or you could add the "IIS Management Console" through installing Windows Features -> Internet Information Services ->IIS Management Console.

**Comment by davidcie** [comment]
Thank you for coming back so quickly. Sure understand that we cannot redist MS assemblies. Unfortunately, I was so set on finding the correct SDK that it never occurred to me I could try simply peeking around my filesystem to find the missing dll! Project builds just fine now and hence closing this "non-issue".

Perhaps if you find it reasonable, at some point in the future you could add your helpful instructions above to the readme so more blind people such as myself will be able to make use of your great fork!
